### ISSUE TITLE
Rock 9.1 import failure - Invalid column name 'MetaPersonicxLifestageClusterId'

### ISSUE THREAD

**Issue by ElimAdmin** [KingdomFirst/Bulldozer#18]
Trying to import Family.csv record into Rock version 

Rock Version: Rock McKinley 9.1 (1.9.1.3)
Client Culture Setting: en-NZ

Family.csv

FamilyId,FamilyName,CreatedDate,Campus,Address,Address2,City,State,Zip,Country,SecondaryAddress,SecondaryAddress2,SecondaryCity,SecondaryState,SecondaryZip,SecondaryCountry 
20190907001,Mroach,2019-09-08,,,,,,,,,,,,,

Getting the following error:

![bulldozer1](https://user-images.githubusercontent.com/4658177/64484159-36d0eb00-d1c3-11e9-8c01-0765a62b0bce.jpg)

![bulldozer2](https://user-images.githubusercontent.com/4658177/64484161-3a647200-d1c3-11e9-962f-c71f102433ae.jpg)

![bulldozer3](https://user-images.githubusercontent.com/4658177/64484163-3e908f80-d1c3-11e9-9e1f-880d0ade15db.jpg)

![bulldozer4](https://user-images.githubusercontent.com/4658177/64484164-42241680-d1c3-11e9-9981-63e310547460.jpg)

![bulldozer5](https://user-images.githubusercontent.com/4658177/64484168-44867080-d1c3-11e9-8590-2a53b0c3bbbc.jpg)

**Comment by mattbaylor** [comment]
We are not yet supporting Rock v9 with Bulldozer. While it is on our roadmap to update Bulldozer to support Rock v9 we do not yet have a timeframe established for that effort. That being said we welcome any and all contributions that will make Bulldozer a better tool for the entire community.

**Comment by ElimAdmin** [comment]
@mattbaylor 
Thanks Mat.  Might be an idea to make this clear in the documentation.  I wish I could code and help.

Help me understand:  Is this likely to happen with subsequent versions of Rock?  If I'm building processes that rely on using Bulldozer to upload, and it breaks on version changes, this is a risk.  E.g. importing financial transactions from our financial system.

**Comment by mattbaylor** [comment]
Hey Ken, I added a version to the requirements of the readme. I'd like to keep the documentation as version agnostic as possible so that we don't have to scrub a bunch of documentation when we do support a new version.

Version support is really a function of time and money. When we either have the time, or find someone who is willing to fund the effort to support the next version then we will add support the next version.

**Comment by ElimAdmin** [comment]
@mattbaylor I understand.  Give me an idea of the cost to add support for v9.  You can email me at
![email](https://user-images.githubusercontent.com/4658177/64642482-56cefd00-d3c3-11e9-802a-ba82ae25a116.jpg)

**Comment by nateh777** [comment]
Bulldozer with Rock v9.2 support has been released: https://github.com/KingdomFirst/Bulldozer/releases/tag/1.9.2.5.20191114

Please let us know if you are still experiencing this issue with the latest release. Otherwise we will close this issue. Thank you!
