### ISSUE TITLE
Exception Errors when importing Individual.csv

### ISSUE THREAD

**Issue by ekabvunye** [KingdomFirst/Bulldozer#29]
Hi
Its my first attempt to Use the Bulldozer utility to try and import a small sample record into a test Rock rms database. The database is running on the latest 10.2 version of rock rms.

When I tried uploading an individual.csv file, I got exceptions captured in the attached log files.  Is it me not following the correct procedure. 
Please assist
[BulldozerExceptions.txt](https://github.com/KingdomFirst/Bulldozer/files/4500113/BulldozerExceptions.txt)

**Comment by mattbaylor** [comment]
Hey @ekabvunye, we have not yet added support for Rock v10. It is in our plans, but we do not yet have timing for it. Thanks for reporting this, and we will resolve v10 issues when we officially support v10.

**Comment by buddy409** [comment]
Is there an estimated date where v10 will be supported?  It has been around for several months already

**Comment by nateh777** [comment]
v10.2 support was released yesterday. Please let us know if you continue to see any issues: https://github.com/kingdomfirst/bulldozer/releases
