### ISSUE TITLE
B: CSV - Attributes Not Importing rock v10.2 

### ISSUE THREAD

**Issue by hkvogeler** [KingdomFirst/Bulldozer#31]
# Prerequisites
**We will take your suggestion into consideration, however, if you would like to sponsor this change, please email sales@kingdomfirstsolutions.com and we will process an estimate for you.**

**Otherwise, bugs will be addressed in the order of criticality, and enhancements will be addressed as sponsored, or as we have the available bandwidth. Note: Our code may not be vetted for, and may not support early release Rock versions only general release Rock versions.**

Please answer the following questions for yourself before submitting an issue. 

- [ X] I have classified my issue according to the following rules:

**Bug Classifications:**

_Enhancement:_ A desired change to the code that enhances functionality verses fixing an issue.   

_Bug:_ Updating code to work as originally designed.

- [X ] I am running the latest version
- [X ] I checked to make sure that this issue has not already been filed
- [ ] I've named my issue either `B:` or `E:` depending on whether it is a bug or an enhancement

# Expected Behavior

Attribute values to be imported either 1) with 01 individual (tried several iterations of the ^ listing in header. 2) 24-entity attribute value import not saving any items.

# Current Behavior

1) individuals import & families created but no attribute values are recorded.
2) not attribute values recorded

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version: 10.2
* Bulldozer Version: 1.9.2.5.20191114
* SQL Server Version: 15.0.2000.5
* Windows Version: Windows Server 2019 Standard

## Failure Logs
***
2

:15:55 PM  Starting health checks...
2:16:06 PM  Checking for existing data...
2:16:08 PM  Starting data import...
2:16:09 PM  Verifying attribute value import (0 already imported).
2:16:09 PM  Finished attribute value import: 0 attribute values imported.
2:16:09 PM  Completed import: 1 rows processed.
***
Please include any relevant log snippets or files here.

**Comment by guymaness2** [comment]
We have seen no issues with attributes importing in Bulldozer via csv files when properly configured. That being said, Bulldozer was not yet compatible with v10 of Rock when this issue was posted. We actually just updated the package yesterday (6/16/2020) to officially support v10. I recommend downloading the new release files and trying again to see if that solves your problem.

**Comment by hkvogeler** [comment]
Thank you for the update, we’re in the process of updating to the new version on our sandbox.

H. Kurt Vogeler, SPHR, SHRM-SCP
Director of Human Resources
Email: kurtvogeler@tfc.org<mailto:kurtvogeler@tfc.org>
Office: 806.677.1005  *  Fax: 806.463.2623
[TF_Logo]
www.TFC.org<http://www.tfc.org/>  *  806.355.8955  *  5000 Hollywood, Amarillo, TX 79118

**Comment by hkvogeler** [comment]
error seems to be result of old Bulldozer version with 10.2 Rock.. new Bulldozer with 10.2 attributes work as expected.
