### ISSUE TITLE
Could not import batch.csv only because could not find Anonymous Giver user

### ISSUE THREAD

**Issue by ElimAdmin** [KingdomFirst/Bulldozer#5]
Thank you for your work on extending this tool.  
Importing a Batch.csv only (no other files) with one header line and one detail line, with 
 <add key="RequireAnonymousGiver" value="true" />.

Import failed with error message

 LogException( "CheckExistingImport", "The named Anonymous Giving user was not found, and none could be created." );

I tried creating a person in the database with 
Firstname=Anonymous, Lastname=Giver
Firstname=Anonymous Giver

But couldn't get past this error.

I suggest a clearer error message like: "The Person with FirstName=Anonymous and LastName=Giver was not found in the database.  Create this user and try again."

I was able to import that Batch.csv by setting 
 <add key="RequireAnonymousGiver" value="false" />.

Rock Version Rock Version: Rock McKinley 8.6 (1.8.6.2)

Client Culture Setting: en-NZ

**Comment by treyhendon** [comment]
@ElimAdmin glad you're still able to use it!

Agreed, need to update the language in that error.  There are two resolutions I see to this by reading the code, each has different impacts.

1. Add a record back to Rock named `Giver Anonymous`  (First: Giver; Last: Anonymous).  This was a generic person record added in life of Rock for taking cash and coins.  [Demo Site Example](https://rock.rocksolidchurchdemo.com/Person/2)
2. In the App.Config file, set the `RequireAnonymousGiver` setting to false.  This could have impact, however, if the gift being imported is not properly mapped to a person in the database.

Think of changing the error to:
```
The record for anonymous giving could not be found, please add a person named Giver Anonymous.  Optionally, consider disabling RequireAnonymousGiver in the App.Config file.
```

**Comment by ElimAdmin** [comment]
@treyhendon 
Ah! I didn't try First:Giver, Last: Anonymous.
Maybe the message could read: ...add a person with first name 'Giver' and last name 'Anonymous.'

Can I help you with the wiki documentation again?

**Comment by treyhendon** [comment]
Absolutely!  Just sent you an invite.  Thanks!
