### ISSUE TITLE
Thanks for this great tool but i got and error while trying to test the tool with our Rock RMS : the error is when i tried to upload the CSV template i got this error : 

### ISSUE THREAD

**Issue by Peter-Shawky** [KingdomFirst/Bulldozer#63]
# Prerequisites
**We will take your suggestion into consideration, however, if you would like to sponsor this change, please email sales@kingdomfirstsolutions.com and we will process an estimate for you.**

**Otherwise, bugs will be addressed in the order of criticality, and enhancements will be addressed as sponsored, or as we have the available bandwidth. Note: Our code may not be vetted for, and may not support early release Rock versions only general release Rock versions.**

Please answer the following questions for yourself before submitting an issue. 

- [ ] I have classified my issue according to the following rules:

**Bug Classifications:**

_Enhancement:_ A desired change to the code that enhances functionality verses fixing an issue.   

_Bug:_ Updating code to work as originally designed.

- [ ] I am running the latest version
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I've named my issue either `B:` or `E:` depending on whether it is a bug or an enhancement

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue. 

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Rock Version:
* Bulldozer Version: 
* SQL Server Version:
* Windows Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by nateh777** [comment]
There is no content in this issue submission.
