### ISSUE TITLE
ENH: Add a RESTART button to Import Complete page

### ISSUE THREAD

**Issue by ElimAdmin** [KingdomFirst/Bulldozer#7]
Allow user to start over again from first page to import a new file, on successful completion of import.  Add a 'RESTART' or 'IMPORT NEW FILE' button to the Import Complete page.

**Comment by treyhendon** [comment]
This is a lower priority enhancement at this time.  Since multiple versions of the same CSV type can be loaded, there is little compelling reason to need to restart after a map finishes.  

CSV files need to end-with the map name.  Binary Files need to begin-with the map name.
